name: Docker image builds
on:
  push:
    branches:
      - main
    paths:
      - ./**
  workflow_dispatch:

jobs:
  backup-db:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "dearrow-awards"
      username: "ajayyy"
      folder: "."
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}